# Generated by Django 3.1.3 on 2020-11-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201114_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_table',
            new_name='TableUser',
        ),
        migrations.AlterModelTable(
            name='tableuser',
            table='table_user',
        ),
    ]
